variables:
  #versioning variable
  MAJOR_VER: "1"
  MINOR_VER: "0"
  #deployment variable
  CONTAINER_REGISTRY_PROJECT_ID: "${CI_PROJECT_ID}-${CI_PROJECT_NAME}"

stages:
  - build
  - test
  - predeploy

include:
#  - local: '/.gitlab-ci-build.yml'
  - local: '/.gitlab-ci-sonarcloud.yml'
#  - local: '/.gitlab-ci-test.yml'
#  - local: '/.gitlab-ci-predeploy.yml'
